# Docker image for bigfoot

DOCKER_BIGFOOT_STEM = docker-bigfoot
DOCKER_BIGFOOT = $(DOCKER_BIGFOOT_STEM).gz
DOCKER_BIGFOOT_DBG = $(DOCKER_BIGFOOT_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_BIGFOOT)_PATH = $(DOCKERS_PATH)/$(DOCKER_BIGFOOT_STEM)

$(DOCKER_BIGFOOT)_DEPENDS += $(REDIS_TOOLS)
#$(DOCKER_BIGFOOT)_PYTHON_DEBS += $(SONIC_UTILS)
$(DOCKER_BIGFOOT)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_STRETCH)_DBG_DEPENDS)

$(DOCKER_BIGFOOT)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_STRETCH)_DBG_IMAGE_PACKAGES)

$(DOCKER_BIGFOOT)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_STRETCH)

SONIC_DOCKER_IMAGES += $(DOCKER_BIGFOOT)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_BIGFOOT)
SONIC_STRETCH_DOCKERS += $(DOCKER_BIGFOOT)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_BIGFOOT_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_BIGFOOT_DBG)
SONIC_STRETCH_DBG_DOCKERS += $(DOCKER_BIGFOOT_DBG)

$(DOCKER_BIGFOOT)_CONTAINER_NAME = bigfoot
$(DOCKER_BIGFOOT)_RUN_OPT += --net=host --privileged -t
$(DOCKER_BIGFOOT)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_BIGFOOT)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
